baseURL = 'https://awesome-go-lang.github.io/'
languageCode = 'en-us'
title = 'Awesome Golang'
theme = 'beautifulhugo'
summaryLength = 25
copyright = "Harendra Kumar"
disqusShortname = "shortDisquis"
googleAnalytics = "UA-1XXXXXXX1-X"
pygmentsCodeFences = true