baseURL = 'https://golang.withcodeexample.com/'
languageCode = 'en-us'
title = 'Golang With Code Example'
theme = 'mytheme'
summaryLength = 25
copyright = "Harendra Kumar Kanojiya"
disqusShortname = "awesome-golang"
#googleAnalytics = "UA-1XXXXXXX1-X"
pygmentsCodeFences = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
enableRobotsTXT = true
paginate = 10

[markup.goldmark.renderer]
  unsafe= true

[Imports]
  path= 'github.com/HugoBlox/hugo-blox-builder/tree/main/modules/blox-plugin-decap-cms'

[Params]
  homeTitle = 'Golang'
  description = "Master Golang programming with our comprehensive tutorials and practical examples. Learn Golang syntax, best practices, and advanced concepts to become a skilled developer."
  title = 'Golang With Code Example'
  subtitle = "Learn with working Examples and Audio summary"
  mainSections = ["blog"]
  logo = "https://res.cloudinary.com/harendra21/image/upload/w_100/With_Code_Example_pemcaz.png" # Expecting square dimensions
  favicon = "https://res.cloudinary.com/harendra21/image/upload/w_400/With_Code_Example_pemcaz_nzrfh9.png"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = true
#  gcse = "667de25a4f13c494d" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."
  timeZone = "Asia/Kolkata"
  generateTOC = true
  isAlgolia=true
  algoliaAppId='EIJKO78J39'
  algoliaApiKey='5842312573fcdf13466a8d483aea2708'
  algoliaSiteId='c652f3fe-7295-4bce-b960-958a88add0a5'
  isGgoogleAnalytics=true
  googleAnalytics = "G-GQKKYY4MGH"
  googleSiteVarify='Q7NS0IbakCR3A0QWxE1ka9o2xThUBLTCuIbD750UFgU'

[taxonomies]
   series = "series"
   tags = "tags"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "With Code Example"
  website = "https://withcodeexample.com"
  # email = "harendraverma21@gmail.com"
  # facebook = "harendraverma21"
  github = "awesome-blog"
  #gitlab = "username"
  #bitbucket = "username"
  # twitter = "harendraverma2"
  #reddit = "username"
  # linkedin = "harendra21/"
  #xing = "username"
  # stackoverflow = "users/6720451/harendra-kumar"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #elegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #eibo = "username"
  #slack = "username"
  #medium = "username"
  #discord = "invite code (https://discord.gg/XXXXXXX)"
  #strava = "userid"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
  name = "Courses"
  weight = 2
  url = "https://courses.withcodeexample.com/course/"
  identifier = "courses"

[[menu.main]]
  name = "Sites"
  weight = 3
  identifier = "sites"

[[menu.main]]
  parent = "sites"
  name = "Golang"
  url = "https://golang.withcodeexample.com/"
  weight = 1

[[menu.main]]
  parent = "sites"
  name = "Javascript"
  url = "https://javascript.withcodeexample.com/"
  weight = 2

[[menu.main]]
  parent = "sites"
  name = "Courses"
  url = "https://courses.withcodeexample.com/"
  weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[[menu.main]]
    name = "Discord"
    url = "https://discord.gg/hS2EqYqM"
    weight = 5